# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest #windows-latest #macos-latest

steps:
  - task: UseNode@1
    inputs:
      version: '24.x'
    displayName: 'Install Node.js'
    
  - script: npm ci
    displayName: 'Install Playwright Dependencies'

  - script: npx playwright install --with-deps
    displayName: 'Install Playwright Browsers'
  
  - script: SECRET_KEY=$(SECRET_KEY_VAL) npm run test_demo
    displayName: 'Run Tests'